### ISSUE TITLE
Questions about the results in "3.3 NIAPU versus other disease gene identification tools"

### ISSUE THREAD

**Issue by RacconC** [AndMastro/NIAPU#1]
Hello，

I'm curious to know if you utilized a machine learning model to compute the score for this part, or if you derived the results directly from the APU-assigned score. If machine learning models were involved, I'd appreciate guidance on how to obtain scores for diseases with multiple classifications. Thank you in advance for your assistance!

**Comment by AndMastro** [comment]
Hello!

The results you are referring to (Section 3.3 of the [NIAPU paper](https://academic.oup.com/bioinformatics/article/39/2/btac848/7023926)) were obtained using the APU-assigned scores employing the NeDBIT features, with no additional machine learning model 😁
